#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x udiskie > /dev/null || udiskie &

bspc monitor DVI-D-0 -d           1 2 3 4 5
bspc monitor VGA-0 -d             6 7 8 9 0
bspc config border_width          2
bspc config window_gap            20
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config normal_border_color   '#2e3440'
bspc config active_border_color   '#2e3440'
bspc config focused_border_color  '#3b4252'
bspc config presel_feedback_color '#3b4252'

# programs=(xfce-polkit 'eww open bar' picom thunar syncthing)
programs=(xfce-polkit 'eww-x open bar' picom thunar)
for process in "${programs[@]}"; do
	if [[ $(pidof ${process}) ]]; then
		killall -9 ${process}
	fi
done

/usr/lib/xfce-polkit/xfce-polkit &

xsetroot -cursor_name left_ptr

numlockx
wmname LG3D
eww-x open bar
picom &
# syncthing &
~/.fehbg &
thunar --daemon &
