
[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 20
y = 20

[general]
live_config_reload = true
import = ["/home/flame/.config/alacritty/nord.toml", "/home/flame/.config/alacritty/font.toml"]
